export const EMPLOYEE_REPOSITORY = Symbol('EMPLOYEE_REPOSITORY');

export const EMPLOYEE_MAPPER = Symbol('EMPLOYEE_MAPPER');

export const POSITION_REPOSITORY = Symbol('POSITION_REPOSITORY');

export const LOCATION_REPOSITORY = Symbol('LOCATION_REPOSITORY');

export const EMPLOYEE_LOCATION_MAPPER = Symbol('EMPLOYEE_LOCATION_MAPPER');

export const EMPLOYEE_LOCATION_REPOSITORY = Symbol('EMPLOYEE_LOCATION_REPOSITORY');
export const LOCATION_MAPPER = Symbol('LOCATION_MAPPER');

export const MASTER_POSITION_MAPPER = Symbol('MASTER_POSITION_MAPPER');


export const AUTH_PACKAGE_NAME = 'EmployeeService';

export const AUTH_SERVICE_NAME = 'AuthService';

export const AUTH_GRPC_CLIENT = 'AUTH_GRPC_CLIENT';

