export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const MASTER_STATUS_REPOSITORY = Symbol('MASTER_STATUS_REPOSITORY');

export const PASSWORD_SERVICE = Symbol('PASSWORD_SERVICE');
export const JWT_SERVICE = Symbol('JWT_SERVICE');
