syntax = "proto3";

package employee;

service EmployeeService {

  rpc CreateEmployee(CreateEmployeeRequest)
      returns (CreateEmployeeResponse);

  rpc ListEmployee(ListEmployeeRequest)
      returns (ListEmployeeResponse);

  rpc UpdateEmployee(UpdateEmployeeRequest)
      returns (UpdateEmployeeResponse);

  rpc DeleteEmployee(DeleteEmployeeRequest)
      returns (DeleteEmployeeResponse);

  rpc ListPosition(ListPositionRequest)
      returns (ListPositionResponse);

  rpc ListLocation(ListLocationRequest)
      returns (ListLocationResponse);
  
  rpc GetEmployee(GetEmployeeRequest)
      returns(EmployeeResponse);
  
  rpc GetEmployeeByUserId(GetEmployeeRequest)
      returns(EmployeeResponse);

  rpc GetEmployees(GetEmployeesRequest)
      returns(GetEmployeesResponse);
  
}

message CreateEmployeeRequest {

  string employeeNo = 1;

  string fullName = 2;

  string email = 3;

  string password = 4;

  string phone = 5;

  string photoUrl = 6;

  string positionId = 7;

  repeated string locationIds = 8;
}

message CreateEmployeeResponse {

  string employeeId = 1;
}

message GetEmployeeRequest {

  int32 userId = 1;

}



message DeleteEmployeeRequest {

  string employeeId = 1;

}

message DeleteEmployeeResponse {

  bool success = 1;

}

message ListEmployeeRequest {

}

message GetEmployeesResponse {

  repeated EmployeeResponse data = 1;

  int32 page = 2;

  int32 limit = 3;

  int32 total = 4;

}

message EmployeeResponse {

  string employeeId = 1;

  string employeeNo = 2;

  string fullName = 3;

  string phone = 4;

  string photoUrl = 5;

  string positionId = 6;

  string positionName = 7;

  repeated EmployeeLocationResponse locations = 8;

}

message ListEmployeeResponse {

  repeated EmployeeResponse employees = 1;

}

message ListPositionRequest {

}

message PositionResponse {

  string id = 1;

  string code = 2;

  string name = 3;

}

message ListPositionResponse {

  repeated PositionResponse positions = 1;

}

message ListLocationRequest {

}

message LocationResponse {

  string id = 1;

  string locationName = 2;

  string address = 3;

  double latitude = 4;

  double longitude = 5;

  int32 radius = 6;

}

message ListLocationResponse {

  repeated LocationResponse locations = 1;

}

message UpdateEmployeeRequest {

  int32 employeeId = 1;

  string fullName = 2;

  string email = 3;

  string password = 4;

  string phone = 5;

  string photoUrl = 6;

  string positionId = 7;

  repeated string locationIds = 8;
}

message UpdateEmployeeResponse {

  string employeeId = 1;

}


message EmployeeLocation {

    int64 employeeId = 1;

    int64 locationId = 2;

    bool isDefault = 3;

    Location location = 4;

}

message GetEmployeesRequest {

  int32 page = 1;

  int32 limit = 2;

  string search = 3;

  string positionId = 4;

}

message Location {

    int64 id = 1;

    string locationName = 2;

    bool isDefault = 3;

}

message EmployeeLocationResponse {

  string locationId = 1;

  string locationName = 2;

  bool isDefault = 3;

}